type Movie @table {
  title: String!
  releaseYear: Int!
  director: String!
  posterUrl: String!
  synopsis: String
  genre: String
}

type User @table {
  username: String!
  email: String
}

type FavoriteMovie @table(key: ["user", "movie"]) {
  user: User!
  movie: Movie!
  createdAt: Timestamp!
}